### ISSUE TITLE
can_match too lenient

### ISSUE THREAD

**Issue by PSeitz** [tantivy-search/levenshtein-automata#1]
Automaton creation is much faster than from the `fst` crate, although can_match returns too often true and is therefore overall slower for larger datasets, because it traverses a larger part of the fst.

I created a small test to verifiy, with two strings in the fst "foo" and "fshouldearlyaborthere" and apparently it walks the whole fshouldearlyaborthere. I don't understand the ```SINK_STATE```, but it should be possible to do something with ```self.distance(*state)``` to check for early aborts.

```rust

#[cfg(feature="fst_automaton")]
#[cfg(test)]
mod tests_fst {

    use super::fst;
    use super::Distance;
    use super::{LevenshteinAutomatonBuilder};
    use fst::{IntoStreamer, Set};

    #[test]
    fn test_fst() {
        let keys = vec!["foo", "fshouldearlyaborthere"];
        let set = Set::from_iter(keys).unwrap();

        let lev_automaton_builder = LevenshteinAutomatonBuilder::new(0 as u8, true);
        let lev = lev_automaton_builder.build_dfa("foo");

        // Apply our fuzzy query to the set we built.
        let stream = set.search(lev).into_stream();
        let keys = stream.into_strs().unwrap();
        assert_eq!(keys, vec!["foo"]);
    }
}

...Adding println to the Dfa

    fn can_match(&self, state: &u32) -> bool {
        println!("{:?} can_match {:?}",state,  *state != SINK_STATE);
        *state != SINK_STATE
    }

```

```console
 levenshtein-automata git:(master) ✗ cargo test --features fst_automaton test_fst  -- --nocapture
    Finished dev [unoptimized + debuginfo] target(s) in 0.02 secs
     Running target/debug/deps/levenshtein_automata-0acec41aabf8f8fe

running 1 test
4 can_match true
5 can_match true
10 can_match true
5 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
6 can_match true
test tests_fst::test_fst ... ok
```

**Comment by fulmicoton** [comment]
oh thanks for catching that! This certainly looks like a bug.

**Comment by fulmicoton** [comment]
@PSeitz Just fixed it in master. Thanks for the report.

DFAs should get a notch smaller as a result too.

**Comment by fulmicoton** [comment]
(@PSeitz  by the way if you can share the timings of searching an fst in your use case I am interested)

**Comment by PSeitz** [comment]
@fulmicoton Nice, that was quick.

> (@PSeitz by the way if you can share the timings of searching an fst in your use case I am interested)

Sure, I'm mainly testing on 17GB json data, split over 30 fields. The corpus consists mainly of short texts, typically between 1-3 words. Tokens and the complete text is stored in the fst in its original case. Search is done with ignore case (I could create a pull request for this).
https://github.com/PSeitz/levenshtein-automata/blob/3b119a13a34e2cefe7df97b6fc28e6c89295b2f5/src/dfa.rs#L165-L179

When creating large, one per field, fst's (3.6GB total), fst search performance is pretty good for distances 0, 1, and 2 and ranges typically between 0-20ms per field (total fst search time < 80ms). Bottleneck was previously automata creation, which could take around 100ms, but this is not an issue anymore.

Creating very large fst's may not always be feasible, because of the lexicographic order requirement, so I splitted the data in 34 and 166 evenly sized packages and queried them in parallel.

On both packages levenshtein 0 and 1 performs still very good, when there is no memory pressure.
Levenshtein 1 usually doubles the total time.

Due to the random access nature, levenshtein 2 is too slow in the 166 packeted case. I don't know if there is a way to count the jumps in the fst, but we got almost 5000 fst queries * n jumps, which is slow for mmap and in-memory, with the total fst search time above 2 seconds.

So I guess the catch is, when using levenshtein 2, it's advisable trying to reduce the number of fst queries.

Sorry if the numbers are a bit chaotic, but the automated performance tests are unavailable, because some dependencies are broken on nightly.

**Comment by fulmicoton** [comment]
Thanks for the info.

> Creating very large fst's may not always be feasible, because of the lexicographic order requirement, so I splitted the data in 34 and 166 evenly sized packages and queried them in parallel.

I am not following you here. What about creating several fst with pieces of data that fit in your RAM, and then merge them?

> Due to the random access nature, levenshtein 2 is too slow in the 166 packeted case. I don't know if there is a way to count the jumps in the fst, but we got almost 5000 fst queries * n jumps, which is slow for mmap and in-memory, with the total fst search time above 2 seconds.

I am not entirely following something here. The whole fst fit in RAM? If so, you can measure cache misses.

If your use case allow it, one thing that is quite common is to forbid/limit errors on the first few characters. If you force the first char to be correct for instance, your performance should be greatly improved.

This can be implemented without modifying the two crates, by using the range definition API in the StreamBuilder. (token starting by 'a' are `.ge(&[b'a'])` and `.lt(&[b'b')`).

**Comment by PSeitz** [comment]
> I am not following you here. What about creating several fst with pieces of data that fit in your RAM, and then merge them?

Sure, at some point the fst should be merged. I don't know how it's handled in tantivy, but in my case the associated term ids are stored in the fst, which correspond to the lexographic position. So a merge may not be trivial, because of conflicting values. However this was just a test to get some insight, if we would delay fst merge for example in high insert volume scenarios or even just don't merge.

> I am not entirely following something here. The whole fst fit in RAM? If so, you can measure cache misses.

I had some issues with valgrind/vtune and rust, but I think I give it another shot here.

> If your use case allow it, one thing that is quite common is to forbid/limit errors on the first few characters. If you force the first char to be correct for instance, your performance should be greatly improved.

I usually try to avoid performance improvements on cost of search quality. Or is there evidence that tpyos usually don't occur in the first few characters?

**Comment by fulmicoton** [comment]
> Sure, at some point the fst should be merged. I don't know how it's handled in tantivy, but in my case the associated term ids are stored in the fst, which correspond to the lexographic position. So a merge may not be trivial, because of conflicting values. However this was just a test to get some insight, if we would delay fst merge for example in high insert volume scenarios or even just don't merge.

Tantivy also uses the fst to associate a term to a `TermOrdinal` (the position of the given term within the sorted list of terms). The merge logic is not very smart. It works by zipping the different Streams. This is not as optimal as using the  internal structure of the `fst` to merge it, but it works decently and is bounded in RAM too.

> I usually try to avoid performance improvements on cost of search quality. Or is there evidence that tpyos usually don't occur in the first few characters?

Typos supposedly do not happen as often on the first few characters. [Algolia for instance, count them as two typos](https://www.algolia.com/doc/guides/textual-relevance/typo-tolerance/)
