### ISSUE TITLE
Need some precisions on the Distance type

### ISSUE THREAD

**Issue by Kerollmops** [tantivy-search/levenshtein-automata#3]
The `DFA::distance` method returns a `Distance` and the returned values seems wrong to me, I probably need some more explanations on the returned values.

If I understand correctly the `Exact` variant of the `Distance` type means that the word is part on the results because its distance is less or equal to the one specified to create the `DFA` and the other variant (i.e. `AtLeast`) is the distance that is missing to make the word be part of the results (clamped by the `u8` type).

What I didn't understand is that when I ask the `DFA` automaton to match words (i.e. `oreiller`, `oreillers` and `oreilles`) with the `oreiller` query word it returns that `oreiller` is `Exact(1)`, `oreillers` is `Exact(0)` and `oreilles` is `Exact(1)`.

Could you clarify this ? 😃

**Comment by Kerollmops** [comment]
I am not misstyping:

```
querying: "oreiller"
"oreiller", Exact(1)
"oreillers", Exact(0)
"oreilles", Exact(1)
```

**Comment by fulmicoton** [comment]
It sounds like a pretty bag bug O_O

**Comment by fulmicoton** [comment]
I am trying to reproduce without success. Could you copy paste some code to reproduce?

**Comment by fulmicoton** [comment]
The following passes :

```
#[test]
fn test_oreiller() {
    let q: &str = "oreiller";
    for &damerau in [false, true].iter() {
        for i in 0..3 {
            let nfa = LevenshteinNFA::levenshtein(i, damerau);
            let parametric_dfa = ParametricDFA::from_nfa(&nfa);
            let dfa = parametric_dfa.build_dfa(q);
            assert_eq!(dfa.eval("oreiller"), Distance::Exact(0u8));
        }
    }
}
```

**Comment by Kerollmops** [comment]
I am using the master branch of this library, combined with the `fst` library and [the patch I make](https://github.com/BurntSushi/fst/pull/61). I will investigate.

**Comment by Kerollmops** [comment]
Ho ! I probably know ! this is my entire fault, in the patch I make, I return the wrong state !

**Comment by Kerollmops** [comment]
Ok, so I fix the bug [in the patch](https://github.com/BurntSushi/fst/pull/61/files#diff-1b47db5c9a30eca8cfa833e56ecf2c4eR1024).

**Comment by fulmicoton** [comment]
Ok... Looking forward to see your work on https://github.com/BurntSushi/fst/issues/60
